apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: solar-system
type: Opaque
stringData:
  MONGO_URI: mongodb://mongodb:27017/solar-system?authSource=admin
  MONGO_USERNAME: admin
  MONGO_PASSWORD: password
  NODE_ENV: production
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root
  namespace: solar-system
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
